server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/banking_db?createDatabaseIfNotExist=true
    username: root
    password: moha2022
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: NOTIFICATION-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    config:
      enabled: true
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
vonage:
  api:
    key: c29b20a5
    secret: 44tTUtl6ywxhRJhm
topic:
  name: t.transfer-notifications-customer